//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DumperClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DumperClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time,gFx,gFy,gFz,wx,wy,wz,speed,label
        ///0.0,-0.2311,0.0049,0.955,0.0059,-0.0116,0.0012,0.0,1.0
        ///0.010000025711567634,-0.2311,0.0049,0.955,0.0059,-0.0116,0.0012,0.0,1.0
        ///0.020000051423135268,-0.2311,0.0049,0.955,0.0059,-0.0116,0.0012,0.0,1.0
        ///0.0300000771347029,-0.2311,0.0049,0.955,0.0065,-0.0079,0.0012,0.0,1.0
        ///0.040000102846270535,-0.2311,0.0049,0.955,0.0065,-0.0079,0.0012,0.0,1.0
        ///0.05000012855783817,-0.2311,0.0049,0.955,0.0065,-0.0079,0.0012,0.0,1.0
        ///0.0600001542694058,-0.2311,0.0049,0.955,0.0065,-0.0079,0.0012, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Terra_D1_multi_labeled_interpolated {
            get {
                return ResourceManager.GetString("Terra_D1_multi_labeled_interpolated", resourceCulture);
            }
        }
    }
}
